// webui/src/App.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import IconBuild from "~icons/material-symbols/build";
import IconHome from "~icons/material-symbols/home";
import IconSettings from "~icons/material-symbols/settings";
import { MAX_KEYBOX_XML_BYTES } from "./cli";
import { Button } from "./components/atoms/Button";
import { Dialog } from "./components/molecules/Dialog";
import {
	NavigationBar,
	type NavigationItem,
} from "./components/molecules/NavigationBar";
import {
	SettingRowList,
	SettingRowSwitch,
} from "./components/molecules/SettingRow";
import { SnackbarHost, snackbar } from "./components/molecules/Snackbar";
import { TopAppBar } from "./components/molecules/TopAppBar";
import type { SelectedFile } from "./file_selector/file_selector";
import { MODULE_NAME } from "./module_info";
import { fetchLatestSecurityPatch } from "./security_patch";
import { appList, cli, config, fileSelector, keybind } from "./state/app";
import type { Identity } from "./state/identity";
import { useOverlayHistory } from "./state/useOverlayHistory";
import { tr } from "./utils/tr";
import { FileBrowserSheet } from "./views/FileBrowserSheet";
import { GalleryView } from "./views/GalleryView";
import { type ActivityState, HomeView } from "./views/HomeView";
import { SettingsView } from "./views/SettingsView";
import { TargetsView } from "./views/TargetsView";
import { ToolsView } from "./views/ToolsView";

export const APPEARANCE_MODES = ["auto", "light", "dark", "amoled"] as const;
export type AppearanceMode = (typeof APPEARANCE_MODES)[number];

const THEME_KEY = "omk-appearance";
const SCALE_KEY = "omk-ui-scale";
const PAGE_IDS = ["home", "tools", "settings"] as const;

function prefersDark(): boolean {
	return window.matchMedia("(prefers-color-scheme: dark)").matches;
}

export function resolveTheme(
	mode: AppearanceMode,
	systemDark: boolean,
): "light" | "dark" | "amoled" {
	if (mode === "auto") return systemDark ? "dark" : "light";
	return mode;
}

function readStored(
	key: string,
	allowed: readonly string[],
	fallback: string,
): string {
	try {
		const stored = window.localStorage.getItem(key);
		if (stored !== null && allowed.includes(stored)) return stored;
	} catch {
		// Storage is unavailable in some WebView configurations.
	}
	return fallback;
}

function persist(key: string, value: string): void {
	try {
		window.localStorage.setItem(key, value);
	} catch {
		// Persisting the preference is best effort.
	}
}

const EMPTY_IDENTITY: Identity = {
	moduleStatus: "loading" as const,
	keyboxStatus: "loading" as const,
	keyboxSource: "unknown" as const,
	keyboxLevel: "unknown" as const,
	keyboxRevocation: "not_checked" as const,
	teeStatus: "loading" as const,
	securityPatch: null,
	soterSpoofEnabled: undefined,
	selectedCount: 0,
};

export function App(): React.JSX.Element {
	const [page, setPage] = useState(0);
	const [identity, setIdentity] = useState(EMPTY_IDENTITY);
	const [activity, setActivity] = useState<ActivityState>({
		status: "loading",
		entries: [],
	});
	const [appearance, setAppearance] = useState(() =>
		readStored(THEME_KEY, APPEARANCE_MODES, "auto"),
	);
	const [scale, setScale] = useState(() => readStored(SCALE_KEY, [], "100"));
	const [systemDark, setSystemDark] = useState<boolean>(prefersDark);
	const [patchBusy, setPatchBusy] = useState<"sync" | "restore" | null>(null);
	const [activityClearBusy, setActivityClearBusy] = useState(false);
	const [keyboxFile, setKeyboxFile] = useState<SelectedFile | null>(null);
	const [keyboxBusy, setKeyboxBusy] = useState(false);
	const [adbOpen, setAdbOpen] = useState(false);
	const [soterOpen, setSoterOpen] = useState(false);
	const [targetsOpen, setTargetsOpen] = useState(false);
	// Modal layers owned by a child view, reported up so Escape closes exactly
	// one layer at a time.
	const [targetsOverlayOpen, setTargetsOverlayOpen] = useState(false);
	const [fileSelectorOpen, setFileSelectorOpen] = useState(false);

	useEffect(() => {
		const query = window.matchMedia("(prefers-color-scheme: dark)");
		const onChange = (event: MediaQueryListEvent): void =>
			setSystemDark(event.matches);
		query.addEventListener("change", onChange);
		return () => query.removeEventListener("change", onChange);
	}, []);

	useEffect(() => {
		document.documentElement.dataset.theme = resolveTheme(
			appearance as AppearanceMode,
			systemDark,
		);
		persist(THEME_KEY, appearance);
	}, [appearance, systemDark]);

	useEffect(() => {
		document.documentElement.style.setProperty(
			"--omk-ui-scale",
			String(Number(scale) / 100),
		);
		persist(SCALE_KEY, scale);
	}, [scale]);

	/*
	 * Overlays join the browser history stack so the Android back gesture
	 * closes the topmost one. The host intercepts back presses and hands them
	 * to the page, which is the only way a native WebView back button can
	 * reach React state.
	 */
	useOverlayHistory([
		{ key: "targets", open: targetsOpen, close: () => setTargetsOpen(false) },
		{
			key: "keybox",
			open: keyboxFile !== null,
			close: () => setKeyboxFile(null),
		},
		{ key: "adb", open: adbOpen, close: () => setAdbOpen(false) },
		{ key: "soter", open: soterOpen, close: () => setSoterOpen(false) },
	]);

	// Read through a ref so the handler is registered once: Keybind has no
	// unsubscribe, and re-registering would stack duplicate handlers.
	const escapeTarget = useRef({ targetsOpen: false, dialogOpen: false });
	escapeTarget.current = {
		targetsOpen,
		dialogOpen:
			keyboxFile !== null ||
			adbOpen ||
			soterOpen ||
			targetsOverlayOpen ||
			fileSelectorOpen,
	};

	useEffect(() => {
		keybind.on("keybind-esc", () => {
			const state = escapeTarget.current;
			// Returning false leaves the event alone so Headless UI can close
			// its own dialog; one Escape must never close two layers.
			if (state.dialogOpen || !state.targetsOpen) return false;
			setTargetsOpen(false);
			return true;
		});
	}, []);

	const refreshIdentity = useCallback(async () => {
		await config.read().catch((error: unknown) => {
			console.error("Unable to load the OMK configuration:", error);
		});
		await appList.fetch().catch((error: unknown) => {
			console.error("Unable to load installed packages:", error);
		});
		const count = appList.getSelectedCount();
		const { identity: next, activity: nextActivity } = await import(
			"./state/identity"
		).then(({ loadIdentity }) => loadIdentity(count));
		setIdentity(next);
		setActivity(nextActivity);
	}, []);

	useEffect(() => {
		void refreshIdentity();
	}, [refreshIdentity]);

	const onAppearanceChange = useCallback((next: string) => {
		if ((APPEARANCE_MODES as readonly string[]).includes(next))
			setAppearance(next);
	}, []);

	const clearActivity = useCallback(async () => {
		setActivityClearBusy(true);
		try {
			await cli.clearActivityLog();
			setActivity({ status: "ready", entries: [] });
			snackbar.show(tr("home_activity_cleared", "Activity cleared."));
		} catch (error) {
			snackbar.show(
				error instanceof Error ? error.message : String(error),
				"error",
			);
		} finally {
			setActivityClearBusy(false);
		}
	}, []);

	/**
	 * Delegates to the ported selector rather than a bare <input type="file">.
	 * It requests every MIME type, because Android document providers
	 * frequently do not report XML correctly; it validates the extension and
	 * size; it handles the picker's cancel path on WebViews that never fire a
	 * change event; and it falls back to the shared-storage browser when the
	 * WebView refuses to open a chooser at all.
	 */
	const chooseKeybox = useCallback(async () => {
		try {
			const selected = await fileSelector.getSystemFileContent("xml");
			if (selected !== null) setKeyboxFile(selected);
		} catch (error) {
			snackbar.show(
				error instanceof Error ? error.message : String(error),
				"error",
			);
		}
	}, []);

	const installKeybox = useCallback(async () => {
		if (keyboxFile === null) return;
		setKeyboxBusy(true);
		try {
			await cli.installKeybox(keyboxFile.contents);
			setKeyboxFile(null);
			snackbar.show(tr("prompt_keybox_replaced", "Keybox replaced."));
			await refreshIdentity();
		} catch (error) {
			snackbar.show(
				error instanceof Error ? error.message : String(error),
				"error",
			);
		} finally {
			setKeyboxBusy(false);
		}
	}, [keyboxFile, refreshIdentity]);

	const runPatchAction = useCallback(
		async (mode: "sync" | "restore") => {
			setPatchBusy(mode);
			try {
				if (mode === "restore") {
					await cli.restoreDefaultSecurityPatch();
					snackbar.show(
						tr(
							"prompt_security_patch_restored_default",
							"Default security patch restored. Please reboot the device.",
						),
					);
				} else {
					const date = await fetchLatestSecurityPatch(() =>
						cli.fetchSecurityBulletin(),
					);
					const applied = await cli.syncSecurityPatch(date);
					snackbar.show(
						tr(
							"prompt_security_patch_sync_complete",
							"Security patch set to %s. Please reboot the device.",
							applied,
						),
					);
				}
				await refreshIdentity();
			} catch (error) {
				snackbar.show(
					error instanceof Error ? error.message : String(error),
					"error",
				);
			} finally {
				setPatchBusy(null);
			}
		},
		[refreshIdentity],
	);

	const navItems: NavigationItem[] = [
		{ id: PAGE_IDS[0], label: tr("nav_home", "Home"), icon: IconHome },
		{ id: PAGE_IDS[1], label: tr("nav_tools", "Tools"), icon: IconBuild },
		{
			id: PAGE_IDS[2],
			label: tr("nav_settings", "Settings"),
			icon: IconSettings,
		},
	];

	if (
		import.meta.env.DEV &&
		new URLSearchParams(window.location.search).has("gallery")
	) {
		return (
			<>
				<GalleryView
					theme={resolveTheme(appearance as AppearanceMode, systemDark)}
					appearance={appearance}
					onAppearanceChange={onAppearanceChange}
				/>
				<SnackbarHost />
			</>
		);
	}

	return (
		<div
			className="flex min-h-dvh flex-col bg-omk-bg text-omk-on"
			data-testid="omk-app"
		>
			{/*
			 * The app bar names the module, not the page: the navigation bar
			 * already marks which page is current, so repeating it here was
			 * redundant and cost the title its width.
			 */}
			<TopAppBar title={MODULE_NAME} />

			<main className="flex-1">
				{page === 0 ? (
					<HomeView
						identity={identity}
						activity={activity}
						activityClearBusy={activityClearBusy}
						onClearActivity={() => void clearActivity()}
						onOpenTargets={() => setTargetsOpen(true)}
					/>
				) : null}
				{page === 1 ? (
					<ToolsView
						busy={patchBusy}
						onOpenTargets={() => setTargetsOpen(true)}
						onInstallKeybox={() => void chooseKeybox()}
						onSyncPatch={() => void runPatchAction("sync")}
						onRestorePatch={() => void runPatchAction("restore")}
						onOpenAdbDisabler={() => setAdbOpen(true)}
						onOpenSoter={() => setSoterOpen(true)}
					/>
				) : null}
				{page === 2 ? (
					<SettingsView
						appearance={appearance}
						onAppearanceChange={onAppearanceChange}
						scale={Number(scale)}
						onScaleChange={(value) => setScale(String(value))}
					/>
				) : null}
			</main>

			<NavigationBar items={navItems} value={page} onChange={setPage} />

			{targetsOpen ? (
				<TargetsView
					onClose={() => setTargetsOpen(false)}
					onSaved={() => void refreshIdentity()}
					onNotify={(message, error) =>
						snackbar.show(message, error === true ? "error" : "normal")
					}
					onOverlayChange={setTargetsOverlayOpen}
				/>
			) : null}

			<FileBrowserSheet onOpenChange={setFileSelectorOpen} />

			<Dialog
				open={keyboxFile !== null}
				onClose={() => (keyboxBusy ? undefined : setKeyboxFile(null))}
				title={tr("replace_keybox_title", "Replace keybox.xml")}
			>
				<p className="text-omk-body text-omk-muted">
					{keyboxFile?.name} · {keyboxFile?.contents.byteLength ?? 0} /{" "}
					{MAX_KEYBOX_XML_BYTES} bytes
				</p>
				<div className="mt-4 flex justify-end gap-2">
					<Button
						variant="secondary"
						disabled={keyboxBusy}
						onClick={() => setKeyboxFile(null)}
					>
						{tr("functional_button_cancel", "Cancel")}
					</Button>
					<Button busy={keyboxBusy} onClick={() => void installKeybox()}>
						{tr("functional_button_replace", "Replace")}
					</Button>
				</div>
			</Dialog>

			<SoterDialog
				open={soterOpen}
				onClose={() => setSoterOpen(false)}
				onChanged={refreshIdentity}
			/>
			<AdbDialog
				open={adbOpen}
				onClose={() => setAdbOpen(false)}
				onApplied={() => {
					setAdbOpen(false);
					void refreshIdentity();
				}}
			/>
			<SnackbarHost />
		</div>
	);
}

interface SoterDialogProps {
	open: boolean;
	onClose: () => void;
	onChanged: () => Promise<void>;
}

function SoterDialog({ open, onClose, onChanged }: SoterDialogProps) {
	const [state, setState] = useState<{
		enabled: boolean;
		reboot_required: boolean;
	} | null>(null);
	const [busy, setBusy] = useState(false);

	useEffect(() => {
		if (!open) return;
		setState(null);
		cli.getSoterSpoofState().then(setState, (error: unknown) => {
			snackbar.show(
				error instanceof Error ? error.message : String(error),
				"error",
			);
			onClose();
		});
	}, [open, onClose]);

	const apply = useCallback(
		async (enabled: boolean) => {
			setBusy(true);
			try {
				setState(await cli.setSoterSpoofEnabled(enabled));
				snackbar.show(
					enabled
						? tr(
								"prompt_soter_spoof_enabled",
								"Soter spoofing enabled. Reboot to apply.",
							)
						: tr("prompt_soter_spoof_disabled", "Soter spoofing disabled."),
				);
				await onChanged();
			} catch (error) {
				snackbar.show(
					error instanceof Error ? error.message : String(error),
					"error",
				);
			} finally {
				setBusy(false);
			}
		},
		[onChanged],
	);

	return (
		<Dialog
			open={open}
			onClose={busy ? () => undefined : onClose}
			title={tr("tools_soter_spoofing", "Spoof Soter attestation")}
		>
			<p className="text-omk-caption text-omk-muted">
				{tr("tools_soter_desc", "Present a Soter attestation payload")}
			</p>
			{state === null ? (
				<p className="py-6 text-center text-omk-caption text-omk-muted">
					{tr("home_status_loading", "Checking")}
				</p>
			) : (
				<>
					<SettingRowList className="mt-3">
						<SettingRowSwitch
							controlId="soter-toggle"
							title={tr("tools_soter_spoofing", "Spoof Soter attestation")}
							summary={
								state.reboot_required
									? tr(
											"soter_spoof_reboot_required",
											"Reboot the device to apply this change.",
										)
									: state.enabled
										? tr("soter_spoof_enabled", "Enabled")
										: tr("soter_spoof_disabled", "Disabled")
							}
							checked={state.enabled}
							onChange={(next) => void apply(next)}
							disabled={busy}
						/>
					</SettingRowList>
					<div className="mt-4 flex justify-end">
						<Button variant="secondary" disabled={busy} onClick={onClose}>
							{tr("functional_button_close", "Close")}
						</Button>
					</div>
				</>
			)}
		</Dialog>
	);
}

interface AdbDialogProps {
	open: boolean;
	onClose: () => void;
	onApplied: () => void;
}

function AdbDialog({ open, onClose, onApplied }: AdbDialogProps) {
	const [state, setState] = useState<{
		enabled: boolean;
		dev_options: boolean;
		usb_debug: boolean;
		oem_unlock: boolean;
	} | null>(null);
	const [busy, setBusy] = useState(false);

	useEffect(() => {
		if (!open) return;
		setState(null);
		cli.getAdbDisabler().then(setState, (error: unknown) => {
			snackbar.show(
				error instanceof Error ? error.message : String(error),
				"error",
			);
			onClose();
		});
	}, [open, onClose]);

	const apply = useCallback(async () => {
		if (state === null) return;
		setBusy(true);
		try {
			await cli.setAdbDisabler(
				state.enabled,
				state.dev_options,
				state.usb_debug,
				state.oem_unlock,
			);
			snackbar.show(tr("prompt_adb_disabler_applied", "ADB Disabler applied."));
			onApplied();
		} catch (error) {
			snackbar.show(
				error instanceof Error ? error.message : String(error),
				"error",
			);
		} finally {
			setBusy(false);
		}
	}, [state, onApplied]);

	const rows = [
		[
			"enabled",
			tr("adb_disabler_enabled", "Enabled"),
			tr("adb_disabler_enabled_desc", "Disable ADB on next boot"),
		],
		[
			"dev_options",
			tr("adb_disabler_dev_options", "Developer options"),
			tr("adb_disabler_dev_options_desc", "Hide the developer options entry"),
		],
		[
			"usb_debug",
			tr("adb_disabler_usb_debug", "USB debugging"),
			tr("adb_disabler_usb_debug_desc", "Turn off USB debugging"),
		],
		[
			"oem_unlock",
			tr("adb_disabler_oem_unlock", "OEM unlocking"),
			tr("adb_disabler_oem_unlock_desc", "Turn off OEM unlocking"),
		],
	] as const;

	return (
		<Dialog
			open={open}
			onClose={busy ? () => undefined : onClose}
			title={tr("tools_adb_disabler", "ADB Disabler")}
		>
			<p className="text-omk-caption text-omk-muted">
				{tr("adb_disabler_desc", "Applied on the next boot.")}
			</p>
			{state === null ? (
				<p className="py-6 text-center text-omk-caption text-omk-muted">
					{tr("home_status_loading", "Checking")}
				</p>
			) : (
				<>
					<SettingRowList className="mt-3">
						{rows.map(([key, title, summary], index) => (
							<div key={key}>
								{index > 0 ? <div className="h-px bg-omk-divider" /> : null}
								<SettingRowSwitch
									controlId={`adb-${key}`}
									title={title}
									summary={summary}
									checked={state[key]}
									disabled={busy || (!state.enabled && key !== "enabled")}
									onChange={(next) => setState({ ...state, [key]: next })}
								/>
							</div>
						))}
					</SettingRowList>
					<div className="mt-4 flex justify-end gap-2">
						<Button variant="secondary" disabled={busy} onClick={onClose}>
							{tr("functional_button_cancel", "Cancel")}
						</Button>
						<Button busy={busy} onClick={() => void apply()}>
							{tr("functional_button_apply", "Apply")}
						</Button>
					</div>
				</>
			)}
		</Dialog>
	);
}

// webui/src/vue/App.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import {
  MiuixDialog,
  MiuixIcon,
  MiuixButton,
  MiuixNavigationBar,
  MiuixProgressIndicator,
  MiuixSnackbarHost,
  MiuixSwitchPreference,
  showSnackbar,
  setThemeMode,
} from 'miuix-vue'
import { All, Settings, Tune } from 'miuix-vue/icons'
import { AppList, type AppListSnapshot } from '../app_list/app_list'
import { appearance } from '../appearance'
import { Cli, type ActivityEntry, type KeyboxRevocationStatus } from '../cli'
import { ConfigOhMyKeyMint } from '../config_ohmykeymint'
import { FileSelector } from '../file_selector/file_selector'
import { History } from '../history'
import { i18n } from '../i18n'
import { fetchLatestSecurityPatch } from '../security_patch'
import { isDev } from '../utils/dev'
import HomeView, { type KeyboxStatus, type ModuleStatus, type TeeStatus } from './HomeView.vue'
import SoterSpoofDialog from './SoterSpoofDialog.vue'
import SettingsView from './SettingsView.vue'
import TargetsView from './TargetsView.vue'
import ToolsView, { type ToolEvent } from './ToolsView.vue'
import FileBrowserSheet from './FileBrowserSheet.vue'
import './app.scss'

const cli = new Cli()
const config = new ConfigOhMyKeyMint(cli)
const appList = new AppList(config)
const fileSelector = new FileSelector()
const history = new History()

const pageIndex = ref(0)
const targetsOpen = ref(false)
const targetsLoading = ref(false)
const snapshot = ref<AppListSnapshot>(appList.getSnapshot())
const moduleStatus = ref<ModuleStatus>('loading')
const keyboxStatus = ref<KeyboxStatus>('loading')
const keyboxSource = ref<'google_hardware' | 'google_remote' | 'unknown'>('unknown')
const keyboxLevel = ref<'tee' | 'strongbox' | 'unknown'>('unknown')
const keyboxRevocation = ref<KeyboxRevocationStatus>('not_checked')
const teeStatus = ref<TeeStatus>('loading')
const securityPatch = ref<string | null>(null)
const soterSpoofEnabled = ref<boolean | undefined>(undefined)
const activities = ref<ActivityEntry[]>([])
const activityStatus = ref<'loading' | 'ready' | 'error'>('loading')
const activityClearBusy = ref(false)
const securityPatchBusy = ref<'sync' | 'restore' | null>(null)
const adbBusy = ref(false)
const adbOpen = ref(false)
const adbEnabled = ref(true)
const adbDevOptions = ref(true)
const adbUsbDebug = ref(true)
const adbOemUnlock = ref(true)
const soterOpen = ref(false)
const keyboxOpen = ref(false)
const selectedKeybox = ref<{ name: string, contents: Uint8Array } | null>(null)
const keyboxBusy = ref(false)
const targetsView = ref<InstanceType<typeof TargetsView> | null>(null)
const soterDialog = ref<InstanceType<typeof SoterSpoofDialog> | null>(null)

const pageIds = ['home', 'tools', 'settings'] as const
const navItems = computed(() => [
  { label: i18n.t('nav_home') === 'nav_home' ? 'Home' : i18n.t('nav_home') },
  { label: i18n.t('nav_tools') === 'nav_tools' ? 'Tools' : i18n.t('nav_tools') },
  { label: i18n.t('nav_settings') === 'nav_settings' ? 'Settings' : i18n.t('nav_settings') },
])

let unsubscribeAppList: (() => void) | null = null
let unsubscribeFileSelector: (() => void) | null = null
let unsubscribeAppearance: (() => void) | null = null
let keydownListener: ((event: KeyboardEvent) => void) | null = null
let pageHistoryActive = false
const overlayHistory = new Set<string>()
let targetsRefreshTimer: number | null = null
let navigationElement: HTMLElement | null = null
let navigationPointerId: number | null = null
let navigationPointerStartX = 0
let navigationPointerStartIndex = 0
let navigationPointerSlotWidth = 1
let navigationWasDragged = false
let navigationSuppressClick = false

function liquidNavigationEnabled(): boolean {
  const root = document.documentElement
  return root.dataset.floatingBottomBar === 'true' && root.dataset.liquidGlass === 'true'
}

function clampNavigationIndex(index: number): number {
  return Math.max(0, Math.min(pageIds.length - 1, index))
}

function navigationPosition(clientX: number): number {
  if (!navigationElement) return pageIndex.value
  const bounds = navigationElement.getBoundingClientRect()
  const slot = Math.max(1, (bounds.width - 8) / pageIds.length)
  return clampNavigationIndex((clientX - bounds.left - 4) / slot)
}

function onNavigationPointerDown(event: PointerEvent): void {
  if (!navigationElement || !liquidNavigationEnabled() || !event.isPrimary || event.button !== 0
      || navigationPointerId !== null) return
  const bounds = navigationElement.getBoundingClientRect()
  navigationPointerSlotWidth = Math.max(
    1,
    (bounds.width - 8) / pageIds.length,
  )
  navigationPointerId = event.pointerId
  navigationPointerStartX = event.clientX
  navigationPointerStartIndex = Math.floor(navigationPosition(event.clientX))
  navigationWasDragged = false
  navigationElement.classList.add('is-pressing')
  navigationElement.style.setProperty('--omk-liquid-nav-index', String(navigationPointerStartIndex))
  navigationElement.style.setProperty('--omk-liquid-nav-scale', '1.392857')
  navigationElement.style.setProperty('--omk-liquid-nav-panel-offset', '0px')
  navigationElement.style.setProperty(
    '--omk-liquid-nav-highlight-x',
    `${event.clientX - bounds.left}px`,
  )
  try { navigationElement.setPointerCapture(event.pointerId) } catch { /* WebView may reject capture. */ }
  event.preventDefault()
}

function onNavigationPointerMove(event: PointerEvent): void {
  if (!navigationElement || navigationPointerId !== event.pointerId) return
  if (Math.abs(event.clientX - navigationPointerStartX) > 1) {
    navigationElement.classList.add('is-dragging')
    navigationWasDragged = true
  }
  const position = navigationPointerStartIndex
    + (event.clientX - navigationPointerStartX) / navigationPointerSlotWidth
  navigationElement.style.setProperty('--omk-liquid-nav-index', String(clampNavigationIndex(position)))
  const bounds = navigationElement.getBoundingClientRect()
  const distance = event.clientX - navigationPointerStartX
  const fraction = Math.min(1, Math.abs(distance) / Math.max(1, bounds.width))
  const rubberBand = Math.sign(distance) * 4 * (1 - (1 - fraction) ** 2)
  navigationElement.style.setProperty('--omk-liquid-nav-panel-offset', `${rubberBand}px`)
  navigationElement.style.setProperty(
    '--omk-liquid-nav-highlight-x',
    `${event.clientX - bounds.left}px`,
  )
  event.preventDefault()
}

function onNavigationPointerUp(event: PointerEvent): void {
  if (!navigationElement || navigationPointerId !== event.pointerId) return
  const target = Math.round(navigationPosition(event.clientX))
  navigationSuppressClick = navigationWasDragged
  navigationPointerId = null
  navigationWasDragged = false
  navigationElement.classList.remove('is-pressing', 'is-dragging')
  navigationElement.style.setProperty('--omk-liquid-nav-scale', '1')
  navigationElement.style.setProperty('--omk-liquid-nav-panel-offset', '0px')
  navigationElement.style.setProperty('--omk-liquid-nav-highlight-x', '50%')
  navigationElement.style.setProperty('--omk-liquid-nav-index', String(target))
  try { navigationElement.releasePointerCapture(event.pointerId) } catch { /* Already released. */ }
  if (target !== pageIndex.value) setPage(target)
  window.setTimeout(() => { navigationSuppressClick = false }, 120)
  event.preventDefault()
}

function onNavigationClickCapture(event: Event): void {
  if (!navigationSuppressClick) return
  navigationSuppressClick = false
  event.preventDefault()
  event.stopImmediatePropagation()
}

function onNavigationPointerCancel(event: PointerEvent): void {
  if (!navigationElement || navigationPointerId !== event.pointerId) return
  navigationPointerId = null
  navigationWasDragged = false
  navigationSuppressClick = false
  navigationElement.classList.remove('is-pressing', 'is-dragging')
  navigationElement.style.setProperty('--omk-liquid-nav-scale', '1')
  navigationElement.style.setProperty('--omk-liquid-nav-panel-offset', '0px')
  navigationElement.style.setProperty('--omk-liquid-nav-highlight-x', '50%')
  navigationElement.style.setProperty('--omk-liquid-nav-index', String(pageIndex.value))
}

function notify(message: string, error = false): void {
  void showSnackbar({ message, duration: error ? 6000 : 'long', withDismissAction: true })
}

function setPage(index: number): void {
  if (index < 0 || index >= pageIds.length || index === pageIndex.value) return
  pageIndex.value = index
  if (index !== 0 && !pageHistoryActive) {
    pageHistoryActive = true
    history.push('main-page', () => {
      pageHistoryActive = false
      pageIndex.value = 0
    })
  } else if (index === 0 && pageHistoryActive) {
    pageHistoryActive = false
    history.consume('main-page')
  }
  window.scrollTo(0, 0)
}

function openTargets(): void {
  if (targetsOpen.value) return
  targetsOpen.value = true
  history.push('app-targets', () => { targetsOpen.value = false })
  window.setTimeout(() => { if (targetsOpen.value) void reloadApps(false) }, 220)
}

function closeTargets(): void {
  if (!targetsOpen.value) return
  targetsOpen.value = false
  if (targetsRefreshTimer !== null) {
    window.clearTimeout(targetsRefreshTimer)
    targetsRefreshTimer = null
  }
  history.consume('app-targets')
}

// Package installation happens outside the WebUI.  Refresh when Android
// brings the WebView back to the foreground so a newly installed app appears
// without requiring the user to close and reopen the selector.  The short
// debounce lets the overlay/focus animation paint before crossing the
// synchronous KernelSU package bridge.
function scheduleTargetsRefresh(): void {
  if (!targetsOpen.value
      || document.visibilityState !== 'visible'
      || targetsLoading.value
      || targetsRefreshTimer !== null) return
  targetsRefreshTimer = window.setTimeout(() => {
    targetsRefreshTimer = null
    if (targetsOpen.value && document.visibilityState === 'visible' && !targetsLoading.value) {
      void reloadApps(false)
    }
  }, 180)
}

function refreshTargetsWhenForegrounded(): void {
  if (document.visibilityState === 'visible') scheduleTargetsRefresh()
}

function onTargetsOverlayOpen(): void {
  const key = 'targets-overlay'
  if (overlayHistory.has(key)) return
  overlayHistory.add(key)
  history.push(key, () => { targetsView.value?.dismissOverlay() })
}

function onTargetsOverlayClose(): void {
  const key = 'targets-overlay'
  if (overlayHistory.delete(key)) history.consume(key)
}

function handleEscape(): void {
  if (targetsOpen.value && targetsView.value?.dismissOverlay()) return
  if (history.size > 0) history.back()
}

async function reloadApps(readConfig: boolean): Promise<void> {
  targetsLoading.value = true
  try {
    if (readConfig) await config.read()
    await appList.fetch()
    appList.syncSystemAppsWithConfig()
    snapshot.value = appList.getSnapshot()
    moduleStatus.value = config.isWritable ? 'ready' : 'error'
  } catch (error) {
    moduleStatus.value = 'error'
    console.error('Unable to load OMK configuration:', error)
    notify(i18n.t('prompt_load_error'), true)
  } finally {
    targetsLoading.value = false
  }
}

async function saveTargets(): Promise<void> {
  targetsLoading.value = true
  try {
    await appList.save()
    snapshot.value = appList.getSnapshot()
    notify(i18n.t('prompt_saved_target'))
    closeTargets()
  } catch (error) {
    console.error('Unable to save OMK targets:', error)
    notify(i18n.t('prompt_save_error'), true)
  } finally {
    targetsLoading.value = false
  }
}

async function refreshIdentity(force = false): Promise<void> {
  // The refresh path always queries the current backend state; keep the
  // parameter for callers that request an explicit refresh after a mutation.
  void force
  if (isDev()) {
    keyboxStatus.value = 'custom'
    keyboxSource.value = 'google_remote'
    keyboxLevel.value = 'tee'
    keyboxRevocation.value = 'not_listed'
    teeStatus.value = 'normal'
    securityPatch.value = '2026-08-01'
    soterSpoofEnabled.value = true
    return
  }
  try {
    const [keybox, patch, tee, soter] = await Promise.allSettled([
      cli.getKeyboxState(),
      cli.getSystemSecurityPatch(),
      cli.getTeeStatus(),
      cli.getSoterSpoofState(),
    ])
    if (keybox.status === 'fulfilled') {
      const value = keybox.value
      keyboxStatus.value = value.valid ? (value.bundled ? 'bundled' : 'custom') : 'invalid'
      keyboxSource.value = value.source
      keyboxLevel.value = value.level
      keyboxRevocation.value = value.valid ? 'checking' : value.revocation
      if (value.valid) {
        try { keyboxRevocation.value = await cli.checkKeyboxRevocation() }
        catch { keyboxRevocation.value = 'unknown' }
      }
    } else keyboxStatus.value = 'error'
    if (patch.status === 'fulfilled') securityPatch.value = patch.value
    if (tee.status === 'fulfilled') teeStatus.value = 'normal'
    else teeStatus.value = 'error'
    soterSpoofEnabled.value = soter.status === 'fulfilled' ? soter.value.enabled : undefined
  } catch (error) {
    console.error('Unable to load OMK identity:', error)
  }
}

async function refreshActivity(): Promise<void> {
  try {
    activities.value = (await cli.getActivityLog()).slice().sort((left, right) => right.timestamp - left.timestamp)
    activityStatus.value = 'ready'
  } catch (error) {
    if (isDev()) {
      const now = Math.floor(Date.now() / 1000)
      activities.value = [{ action: 'keybox_changed', detail: '', timestamp: now - 3600 }]
      activityStatus.value = 'ready'
    } else {
      activityStatus.value = 'error'
      console.error('Unable to load activity:', error)
    }
  }
}

async function chooseKeybox(): Promise<void> {
  try {
    const selected = await fileSelector.getSystemFileContent('xml')
    if (selected) {
      selectedKeybox.value = selected
      keyboxOpen.value = true
    }
  } catch (error) {
    notify(error instanceof Error ? error.message : String(error), true)
  }
}

async function installKeybox(): Promise<void> {
  const selected = selectedKeybox.value
  if (!selected || keyboxBusy.value) return
  keyboxBusy.value = true
  try {
    if (!isDev()) await cli.installKeybox(selected.contents)
    notify(i18n.t('prompt_keybox_replaced'))
    keyboxOpen.value = false
    selectedKeybox.value = null
    await Promise.all([refreshIdentity(true), refreshActivity()])
  } catch (error) {
    notify(i18n.t('prompt_keybox_replace_error', error instanceof Error ? error.message : String(error)), true)
  } finally {
    keyboxBusy.value = false
  }
}

async function syncPatch(restore: boolean): Promise<void> {
  if (securityPatchBusy.value !== null) return
  securityPatchBusy.value = restore ? 'restore' : 'sync'
  try {
    if (restore) {
      if (!isDev()) await cli.restoreDefaultSecurityPatch()
      await refreshIdentity(true)
      notify(i18n.t('prompt_security_patch_restored_default'))
    } else {
      const date = await fetchLatestSecurityPatch(() => cli.fetchSecurityBulletin())
      const applied = isDev() ? date : await cli.syncSecurityPatch(date)
      securityPatch.value = applied
      notify(i18n.t('prompt_security_patch_sync_complete', applied))
    }
    await refreshActivity()
  } catch (error) {
    notify(error instanceof Error ? error.message : String(error), true)
  } finally {
    securityPatchBusy.value = null
  }
}

async function applyAdbDisabler(): Promise<void> {
  if (adbBusy.value) return
  adbBusy.value = true
  try {
    if (!isDev()) {
      await cli.setAdbDisabler(
        adbEnabled.value,
        adbDevOptions.value,
        adbUsbDebug.value,
        adbOemUnlock.value,
      )
    }
    adbOpen.value = false
    notify(i18n.t('prompt_adb_disabler_applied'))
    await refreshActivity()
  } catch (error) {
    notify(error instanceof Error ? error.message : String(error), true)
  } finally {
    adbBusy.value = false
  }
}

function onTool(event: ToolEvent): void {
  switch (event) {
    case 'openAppTargets': openTargets(); break
    case 'installKeybox': void chooseKeybox(); break
    case 'syncSecurityPatch': void syncPatch(false); break
    case 'restoreSecurityPatch': void syncPatch(true); break
    case 'openAdbDisabler': void openAdbDisabler(); break
    case 'spoofSoter': soterOpen.value = true; break
  }
}

async function openAdbDisabler(): Promise<void> {
  if (adbOpen.value) return
  adbOpen.value = true
  if (isDev()) {
    adbEnabled.value = false
    adbDevOptions.value = true
    adbUsbDebug.value = true
    adbOemUnlock.value = true
    return
  }
  try {
    const state = await cli.getAdbDisabler()
    adbEnabled.value = state.enabled
    adbDevOptions.value = state.dev_options
    adbUsbDebug.value = state.usb_debug
    adbOemUnlock.value = state.oem_unlock
  } catch (error) {
    adbOpen.value = false
    notify(error instanceof Error ? error.message : String(error), true)
  }
}

async function clearActivities(): Promise<void> {
  if (activityClearBusy.value) return
  activityClearBusy.value = true
  try {
    if (!isDev()) await cli.clearActivityLog()
    activities.value = []
    notify(i18n.t('home_activity_cleared'))
  } catch (error) {
    notify(error instanceof Error ? error.message : String(error), true)
  } finally {
    activityClearBusy.value = false
  }
}

onMounted(async () => {
  const applyMiuixTheme = (): void => {
    const mode = appearance.mode === 'auto' ? 'system' : appearance.mode === 'amoled' ? 'dark' : appearance.mode
    setThemeMode(mode)
  }
  applyMiuixTheme()
  navigationElement = document.querySelector<HTMLElement>('.main-navigation')
  navigationElement?.style.setProperty('--omk-liquid-nav-index', String(pageIndex.value))
  navigationElement?.style.setProperty('--omk-liquid-nav-scale', '1')
  navigationElement?.addEventListener('pointerdown', onNavigationPointerDown)
  navigationElement?.addEventListener('pointermove', onNavigationPointerMove)
  navigationElement?.addEventListener('pointerup', onNavigationPointerUp)
  navigationElement?.addEventListener('pointercancel', onNavigationPointerCancel)
  navigationElement?.addEventListener('click', onNavigationClickCapture, true)
  unsubscribeAppearance = appearance.onChange(applyMiuixTheme)
  keydownListener = event => {
    if (event.key === 'Escape') {
      event.preventDefault()
      handleEscape()
    }
  }
  window.addEventListener('keydown', keydownListener)
  document.addEventListener('visibilitychange', refreshTargetsWhenForegrounded)
  window.addEventListener('focus', refreshTargetsWhenForegrounded)
  unsubscribeAppList = appList.subscribe(value => { snapshot.value = value })
  unsubscribeFileSelector = fileSelector.subscribe(() => {
    if (fileSelector.open && !overlayHistory.has('file-selector')) {
      overlayHistory.add('file-selector')
      history.push('file-selector', () => fileSelector.cancel())
    } else if (!fileSelector.open && overlayHistory.delete('file-selector')) {
      history.consume('file-selector')
    }
  })
  await Promise.all([reloadApps(true), refreshIdentity(), refreshActivity()])
})

onBeforeUnmount(() => {
  if (targetsRefreshTimer !== null) {
    window.clearTimeout(targetsRefreshTimer)
    targetsRefreshTimer = null
  }
  document.removeEventListener('visibilitychange', refreshTargetsWhenForegrounded)
  window.removeEventListener('focus', refreshTargetsWhenForegrounded)
  if (keydownListener !== null) window.removeEventListener('keydown', keydownListener)
  navigationElement?.removeEventListener('pointerdown', onNavigationPointerDown)
  navigationElement?.removeEventListener('pointermove', onNavigationPointerMove)
  navigationElement?.removeEventListener('pointerup', onNavigationPointerUp)
  navigationElement?.removeEventListener('pointercancel', onNavigationPointerCancel)
  navigationElement?.removeEventListener('click', onNavigationClickCapture, true)
  navigationElement = null
  unsubscribeAppList?.()
  unsubscribeFileSelector?.()
  unsubscribeAppearance?.()
  history.destroy()
})

watch(pageIndex, index => {
  if (navigationPointerId === null) {
    navigationElement?.style.setProperty('--omk-liquid-nav-index', String(index))
  }
})

watch(soterOpen, open => {
  if (open && !overlayHistory.has('soter-spoof')) {
    overlayHistory.add('soter-spoof')
    history.push('soter-spoof', () => {
      overlayHistory.delete('soter-spoof')
      soterDialog.value?.requestClose()
    })
  } else if (!open && overlayHistory.delete('soter-spoof')) history.consume('soter-spoof')
})
watch(adbOpen, open => {
  if (open && !overlayHistory.has('adb-disabler')) {
    overlayHistory.add('adb-disabler')
    history.push('adb-disabler', () => { if (!adbBusy.value) adbOpen.value = false })
  } else if (!open && overlayHistory.delete('adb-disabler')) history.consume('adb-disabler')
})
watch(keyboxOpen, open => {
  if (open && !overlayHistory.has('keybox')) {
    overlayHistory.add('keybox')
    history.push('keybox', () => { if (!keyboxBusy.value) keyboxOpen.value = false })
  } else if (!open && overlayHistory.delete('keybox')) history.consume('keybox')
})
</script>

<template>
  <div class="omk-app">
    <main v-show="!targetsOpen" class="page-host">
      <HomeView
        v-show="pageIndex === 0"
        :keybox-status="keyboxStatus"
        :keybox-source="keyboxSource"
        :keybox-level="keyboxLevel"
        :keybox-revocation="keyboxRevocation"
        :tee-status="teeStatus"
        :security-patch="securityPatch"
        :soter-spoof-enabled="soterSpoofEnabled"
        :activities="activities"
        :activity-status="activityStatus"
        :activity-clear-busy="activityClearBusy"
        @clear-activities="clearActivities"
      />
      <ToolsView
        v-show="pageIndex === 1"
        :security-patch-busy="securityPatchBusy"
        :adb-busy="adbBusy"
        @open-app-targets="onTool('openAppTargets')"
        @install-keybox="onTool('installKeybox')"
        @sync-security-patch="onTool('syncSecurityPatch')"
        @restore-security-patch="onTool('restoreSecurityPatch')"
        @open-adb-disabler="onTool('openAdbDisabler')"
        @spoof-soter="onTool('spoofSoter')"
      />
      <SettingsView v-show="pageIndex === 2" />
    </main>

    <MiuixNavigationBar
      v-show="!targetsOpen"
      :model-value="pageIndex"
      :items="navItems"
      :data-active-index="pageIndex"
      class="main-navigation"
      @update:model-value="setPage"
    >
      <template #icon="{ index }">
        <MiuixIcon :icon="index === 0 ? All : index === 1 ? Tune : Settings" :size="24" />
      </template>
    </MiuixNavigationBar>

    <TargetsView
      v-if="targetsOpen"
      ref="targetsView"
      :app-list="appList"
      :loading="targetsLoading"
      :apply-enabled="snapshot.isWritable"
      @close="closeTargets"
      @refresh="reloadApps(false)"
      @apply="saveTargets"
      @overlay-open="onTargetsOverlayOpen"
      @overlay-close="onTargetsOverlayClose"
    />

    <FileBrowserSheet :selector="fileSelector" />

    <MiuixDialog
      v-model="keyboxOpen"
      :title="i18n.t('replace_keybox_title')"
      :close-on-click-modal="!keyboxBusy"
    >
      <template #default="{ close }">
        <div class="confirm-sheet">
          <p>{{ selectedKeybox ? i18n.t('replace_keybox_selected_file', selectedKeybox.name) : '' }}</p>
          <div class="confirm-actions">
            <MiuixButton :disabled="keyboxBusy" @click="close">
              {{ i18n.t('functional_button_cancel') }}
            </MiuixButton>
            <MiuixButton type="primary" :disabled="keyboxBusy" @click="installKeybox">
              <MiuixProgressIndicator v-if="keyboxBusy" type="circular" :size="18" />
              {{ i18n.t('functional_button_replace') }}
            </MiuixButton>
          </div>
        </div>
      </template>
    </MiuixDialog>

    <MiuixDialog
      v-model="adbOpen"
      :title="i18n.t('tools_adb_disabler')"
      :close-on-click-modal="!adbBusy"
    >
      <template #default="{ close }">
        <div class="confirm-sheet adb-disabler-sheet">
          <p>{{ i18n.t('adb_disabler_desc') }}</p>
          <MiuixSwitchPreference
            v-model="adbEnabled"
            :title="i18n.t('adb_disabler_enabled')"
            :summary="i18n.t('adb_disabler_enabled_desc')"
            :disabled="adbBusy"
          />
          <MiuixSwitchPreference
            v-model="adbDevOptions"
            :title="i18n.t('adb_disabler_dev_options')"
            :summary="i18n.t('adb_disabler_dev_options_desc')"
            :disabled="adbBusy || !adbEnabled"
          />
          <MiuixSwitchPreference
            v-model="adbUsbDebug"
            :title="i18n.t('adb_disabler_usb_debug')"
            :summary="i18n.t('adb_disabler_usb_debug_desc')"
            :disabled="adbBusy || !adbEnabled"
          />
          <MiuixSwitchPreference
            v-model="adbOemUnlock"
            :title="i18n.t('adb_disabler_oem_unlock')"
            :summary="i18n.t('adb_disabler_oem_unlock_desc')"
            :disabled="adbBusy || !adbEnabled"
          />
          <div class="confirm-actions">
            <MiuixButton :disabled="adbBusy" @click="close">{{ i18n.t('functional_button_cancel') }}</MiuixButton>
            <MiuixButton type="primary" :disabled="adbBusy" @click="void applyAdbDisabler()">
              <MiuixProgressIndicator v-if="adbBusy" type="circular" :size="18" />
              {{ i18n.t('functional_button_apply') }}
            </MiuixButton>
          </div>
        </div>
      </template>
    </MiuixDialog>

    <SoterSpoofDialog
      ref="soterDialog"
      v-model="soterOpen"
      :cli="cli"
      @notify="notify"
      @changed="refreshIdentity(true); refreshActivity()"
    />
    <MiuixSnackbarHost />
  </div>
</template>
