// webui/src/vue/ToolsView.vue
<script setup lang="ts">
import {
  MiuixArrowPreference,
  MiuixCard,
  MiuixIcon,
  MiuixProgressIndicator,
  MiuixSmallTitle,
  MiuixTopAppBar,
} from 'miuix-vue'
import { AddCircle, Lock, Replace, Reset, Tune, Update } from 'miuix-vue/icons'
import { i18n } from '../i18n'

export type ToolEvent =
  | 'openAppTargets'
  | 'installKeybox'
  | 'syncSecurityPatch'
  | 'restoreSecurityPatch'
  | 'openAdbDisabler'
  | 'spoofSoter'

type BusyPatch = 'sync' | 'restore' | null

const props = defineProps<{
  securityPatchBusy: BusyPatch
  adbBusy: boolean
}>()

const emit = defineEmits<{
  openAppTargets: []
  installKeybox: []
  syncSecurityPatch: []
  restoreSecurityPatch: []
  openAdbDisabler: []
  spoofSoter: []
}>()

function runTool(event: ToolEvent): void {
  switch (event) {
    case 'openAppTargets': emit('openAppTargets'); break
    case 'installKeybox': emit('installKeybox'); break
    case 'syncSecurityPatch': emit('syncSecurityPatch'); break
    case 'restoreSecurityPatch': emit('restoreSecurityPatch'); break
    case 'openAdbDisabler': emit('openAdbDisabler'); break
    case 'spoofSoter': emit('spoofSoter'); break
  }
}

function tr(key: string, fallback: string): string {
  const value = i18n.t(key)
  return value === key ? fallback : value
}

const groups = [
  {
    title: tr('tools_app_management', 'App management'),
    items: [{
      event: 'openAppTargets' as const,
      icon: AddCircle,
      title: tr('app_targets_title', 'Add package names'),
      summary: tr('tools_app_targets_desc', 'Choose which installed apps are routed through Oh My Keymint.'),
    }],
  },
  {
    title: tr('tools_key_management', 'Key management'),
    items: [
      {
        event: 'installKeybox' as const,
        icon: Replace,
        title: tr('menu_replace_keybox', 'Change Keybox'),
        summary: tr('tools_keybox_desc', 'Choose a Keybox.xml file and install it for Oh My Keymint.'),
      },
      {
        event: 'openAdbDisabler' as const,
        icon: Lock,
        title: tr('tools_adb_disabler', 'ADB Disabler'),
        summary: tr('tools_adb_disabler_desc', 'Disable developer options, USB debugging and OEM unlock at boot.'),
      },
    ],
  },
  {
    title: tr('tools_soter_spoofing', 'Soter spoofing'),
    items: [{
      event: 'spoofSoter' as const,
      icon: Tune,
      title: tr('menu_spoof_soter', 'Spoof Soter attestation'),
      summary: tr('tools_soter_desc', 'Forge healthy Soter responses for Tencent device attestation.'),
    }],
  },
  {
    title: tr('tools_security_patch', 'Set security patch'),
    items: [
      {
        event: 'syncSecurityPatch' as const,
        icon: Update,
        title: tr('menu_sync_security_patch', 'Sync security patch'),
        summary: tr('tools_sync_patch_desc', 'Apply the latest Google security patch date. A reboot is required.'),
      },
      {
        event: 'restoreSecurityPatch' as const,
        icon: Reset,
        title: tr('menu_restore_default_security_patch', 'Restore default security patch'),
        summary: tr('tools_restore_patch_desc', 'Restore the device default security patch date. A reboot is required.'),
      },
    ],
  },
]

function isBusy(event: ToolEvent): boolean {
  if (event === 'openAdbDisabler') return props.adbBusy
  if (event === 'syncSecurityPatch') return props.securityPatchBusy !== null
  if (event === 'restoreSecurityPatch') return props.securityPatchBusy !== null
  return false
}

function isActiveBusy(event: ToolEvent): boolean {
  return (event === 'openAdbDisabler' && props.adbBusy)
    || (event === 'syncSecurityPatch' && props.securityPatchBusy === 'sync')
    || (event === 'restoreSecurityPatch' && props.securityPatchBusy === 'restore')
}
</script>

<template>
  <section class="app-page tools-page" aria-labelledby="tools-title">
    <MiuixTopAppBar id="tools-title" :title="tr('tools_title', 'Tools')" />

    <section v-for="group in groups" :key="group.title" class="preference-section">
      <MiuixSmallTitle :text="group.title" />
      <MiuixCard class="preference-card" press-feedback="none">
        <MiuixArrowPreference
          v-for="item in group.items"
          :key="item.event"
          :title="item.title"
          :summary="item.summary"
          :disabled="isBusy(item.event)"
          :hold-down="isActiveBusy(item.event)"
          @click="runTool(item.event)"
        >
          <template #start>
            <span class="preference-icon">
              <MiuixProgressIndicator
                v-if="isActiveBusy(item.event)"
                type="circular"
                :size="22"
                :stroke-width="2.5"
              />
              <MiuixIcon v-else :icon="item.icon" :size="23" />
            </span>
          </template>
        </MiuixArrowPreference>
      </MiuixCard>
    </section>
  </section>
</template>

// webui/src/views/ToolsView.tsx
import IconApps from "~icons/material-symbols/apps";
import IconKey from "~icons/material-symbols/key";
import IconRefresh from "~icons/material-symbols/refresh";
import IconReset from "~icons/material-symbols/restart-alt";
import IconSecurity from "~icons/material-symbols/security";
import IconShield from "~icons/material-symbols/shield";
import { Divider } from "../components/atoms/Divider";
import { Icon } from "../components/atoms/Icon";
import { SectionHeader } from "../components/molecules/SectionHeader";
import { SettingRow, SettingRowList } from "../components/molecules/SettingRow";
import { tr } from "../utils/tr";

export interface ToolsViewProps {
	busy: "sync" | "restore" | null;
	onOpenTargets: () => void;
	onInstallKeybox: () => void;
	onSyncPatch: () => void;
	onRestorePatch: () => void;
	onOpenAdbDisabler: () => void;
	onOpenSoter: () => void;
}

export function ToolsView({
	busy,
	onOpenTargets,
	onInstallKeybox,
	onSyncPatch,
	onRestorePatch,
	onOpenAdbDisabler,
	onOpenSoter,
}: ToolsViewProps) {
	return (
		<div className="pb-4">
			<SectionHeader>
				{tr("tools_app_management", "App management")}
			</SectionHeader>
			<div className="px-4">
				<SettingRowList>
					<SettingRow
						icon={<Icon as={IconApps} size="md" />}
						title={tr("app_targets_title", "Add package names")}
						summary={tr(
							"tools_app_targets_desc",
							"Choose which apps use this keybox",
						)}
						onPress={onOpenTargets}
					/>
				</SettingRowList>
			</div>

			<SectionHeader>
				{tr("tools_key_management", "Key management")}
			</SectionHeader>
			<div className="px-4">
				<SettingRowList>
					<SettingRow
						icon={<Icon as={IconKey} size="md" />}
						title={tr("menu_replace_keybox", "Change Keybox")}
						summary={tr(
							"tools_keybox_desc",
							"Install a replacement keybox.xml",
						)}
						onPress={onInstallKeybox}
					/>
					<Divider inset />
					<SettingRow
						icon={<Icon as={IconShield} size="md" />}
						title={tr("tools_soter_spoofing", "Spoof Soter attestation")}
						summary={tr(
							"tools_soter_desc",
							"Present a Soter attestation payload",
						)}
						onPress={onOpenSoter}
					/>
				</SettingRowList>
			</div>

			<SectionHeader>
				{tr("tools_security_patch", "Security patch")}
			</SectionHeader>
			<div className="px-4">
				<SettingRowList>
					<SettingRow
						icon={<Icon as={IconRefresh} size="md" />}
						title={tr("menu_sync_security_patch", "Sync security patch")}
						summary={tr(
							"tools_sync_patch_desc",
							"Download the latest bulletin date",
						)}
						disabled={busy !== null}
						onPress={onSyncPatch}
					/>
					<Divider inset />
					<SettingRow
						icon={<Icon as={IconReset} size="md" />}
						title={tr(
							"menu_restore_default_security_patch",
							"Restore default security patch",
						)}
						summary={tr(
							"tools_restore_patch_desc",
							"Go back to the device value",
						)}
						disabled={busy !== null}
						onPress={onRestorePatch}
					/>
				</SettingRowList>
			</div>

			<SectionHeader>{tr("tools_adb_disabler", "ADB Disabler")}</SectionHeader>
			<div className="px-4">
				<SettingRowList>
					<SettingRow
						icon={<Icon as={IconSecurity} size="md" />}
						title={tr("tools_adb_disabler", "ADB Disabler")}
						summary={tr(
							"tools_adb_disabler_desc",
							"Turn off developer options and ADB",
						)}
						onPress={onOpenAdbDisabler}
					/>
				</SettingRowList>
			</div>
		</div>
	);
}
